spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_reddit_clone
    username: root
    password: Lumad
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update
      properties:
        show-sql: true

    ##########################################
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 25
    username: 47bff4adf43d67
    password: 7a84dd6afa4bae
    protocol: smtp


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
